SiLeBAT/FSK-Lab

de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/LibRegistry.java
features/de.bund.bfr.knime.fsklab.feature/CHANGELOG.md
features/de.bund.bfr.knime.fsklab.feature/feature.xml
releng/de.bund.bfr.knime.update/category.xml

- R packages are downloaded and installed even when they are already
installed in other R installations.

## [1.4.3] - 2018-12-19

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeModel.java

The model parameters are initialized from stored input ports in the proper getViewRepresentation implementation.

Initialize JoinerRepresentation from stored ports

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeUtil.java
de.bund.bfr.knime.tests/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeUtilTest.java

Fix Bug FSK-Lab #418: The default simulation of the joiner is now
correctly storing the values of the individual model simulations.

Fix Bug FSK-Lab #418: The default simulation of the joiner is now

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/simulator/JSSimulatorNodeModel.java

#543 fix imports in JSSimulatorNodeModel

removed unused imports

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/runner/RunnerNodeModel.java

#539 Unused parameter in ScriptHandler#runSnippet

removed unused nodeSettings parameter for ScriptHandler#runSnippet

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/FskPortObject.java

#563 Replace duplicated method buildParameterScript with call to
NodeUtils#buildParameterScript.

Remove duplicated method in de.bund.bfr.knime.fsklab.v1_9.FskPortObject

---

de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/creator/CreatorNodeDialog.java
de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/creator/CreatorNodeModel.java

Wrong setting class used in creator node

---

FSKEditorJSNodeModel.java
de.bund.bfr.knime.fsklab.deprecatednodes/js-src/de/bund/bfr/knime/fsklab/nodes/neweditor/editor.js
de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/editor/FSKEditorJSNodeModel.java
de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/joiner/JoinerNodeModel.java
de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/simulator/JSSimulatorNodeModel.java

Take changes from
https://github.com/SiLeBAT/FSK-Lab/tree/abe528d129f7659b2b3f15f97426a2279d468ced

Fix EditorJSNodeModel (missing simulations)

---

de.bund.bfr.knime.fsklab.nodes.tests/files/example_environment.json
de.bund.bfr.knime.fsklab.nodes.tests/src/de/bund/bfr/knime/fsklab/v1_9/FskPortObjectUtilTest.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/FskPortObjectUtil.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/CombinedFskPortObject.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/FskPortObject.java

#597: Created FskPortObjectUtil class with tests to make sure, the class
loader is reset before deserializing the EnvironmentMangager and
GeneratedResourceFiles.

fixed portObject classLoader issue

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/CombinedFskPortObject.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/FskPortObject.java

Remove unused properties in de.bund.bfr.knime.fsklab.v1_9.FskPortObject

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/FskPortObject.java

Drop old metadata in v1_9 FskPortObject.Serializer

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/reader/ReaderNodeModel.java

languageWrittenIn variable now is assigned a default string when
initialized

#635 fix for language_written_in

---

de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/LibRegistry.java

Packages are installed with install.packages into ~/.fsk/library without
using miniCRAN.

Fix package installation on Linux

---

de.bund.bfr.knime.update/category.xml
features/de.bund.bfr.knime.fsklab.feature/feature.xml
features/pom.xml

https://github.com/RakipInitiative/ModelRepository/issues/141

Remove legacy feature and move deprecated nodes to regular feature

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/simulator/jssimulator.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/simulator/JSSimulatorConfig.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/simulator/JSSimulatorNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/simulator/JSSimulatorViewValue.java

#142 simulator now uses default settings

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/writer/WriterNodeDialog.java

https://github.com/RakipInitiative/ModelRepository/issues/144

add .fskx extention to file in writer if it is not given by the user

---

de.bund.bfr.knime.fsklab.nodes.tests/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeUtilTest.java
de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/NodeUtils.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/joiner/JoinerNodeFactory.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/joiner/JoinerNodeFactory.xml
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/joiner/JoinerNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/joiner/JoinerNodeUtil.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/joiner/JoinerViewRepresentation.java

Sorry for the huge PR but it can't be divided more.
Steps to be done after approving this PR are written as //TODO task in code.

648 four optional input port for the joiner

---

de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java

Replace "UTF-8" with StandardCharsets.UTF_8

"StandardCharsets" constants should be preferred (java:S4719)

---

de.bund.bfr.knime.fsklab.deprecatednodes/META-INF/MANIFEST.MF
de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/joiner/JoinerNodeModel.java

I did some testing with Marcels workflow and was able to make only some small changes so that the Joiner now works. It was related to the ObjectMapper not being configured correctly. I am however not sure, if this will break some other model/workflow. Maybe you have a look at it.

changed ObjectMapper in 1.7 Joiner to be able to deserialize icpmf

---

de.bund.bfr.knime.fsklab.metadata.model.tests/src/metadata/ConversionUtilsTest.java
de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java

Finish work of PR https://github.com/SiLeBAT/FSK-Lab/pull/711
The endpoint can be tested with this snippet:
```java
public static void main(String[] args) throws IOException {
ObjectMapper mapper = new ObjectMapper();
GenericModel exampleModel = new GenericModel();
GenericModel secondExample = new GenericModel();
Model[] models = { exampleModel, secondExample };
URL url = new URL("http://localhost:9999/joinMetadata");
HttpURLConnection conn = (HttpURLConnection) url.openConnection();
conn.setRequestMethod("POST");
conn.setRequestProperty("Content-Type", "application/json; utf-8");
conn.setRequestProperty("Accept", "application/json");
conn.setDoOutput(true);
try (OutputStream outputStream = conn.getOutputStream()) {
mapper.writeValue(outputStream, models);
}
// Response
int status = …
```

Finish joining algorithm

---

de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java

Changes error code from 400 to 500. Addresses https://github.com/SiLeBAT/FSK-Lab/issues/732.

Change error code in joinMetadata

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.js

Fix bug of presentation after second run where links between models were not shown.

Fix bug of presentation after second run

---

de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.SelectForm.js

https://github.com/RakipInitiative/ModelRepository/issues/201
and 
another dug reported before related to org.threeten.bp.LocalDate deserialization problem(@schuelet I didn't find the source issue in github)

Editor visual bugs

---

de.bund.bfr.knime.js/src/js/app/app.table.mt.js

this is Sascha work, I just move to fsklab

fix highlight issue

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.js

fix visualization issues in drawing models and min hieght.
fix issue in the generated simulation by removing all input parameterts which are part of join connection

generated simulation issue for joined object

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/runner/RunnerNodeModel.java

@schuelet  solve the previous issue of running a combined model with combined models as submodels

combine two combined fsk objects

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.css
de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.js

zoom in/out buttons are added / mouse wheel zoom support to the joiner area

joiner area zoom in/out

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/RJsonHandler.java

Handler now creates a temp file that stores JSON data. I experienced issues with R not being able to read large json strings, so now it should be much more stable.

fixed some issues if json data is large array

---

de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java

https://github.com/RakipInitiative/ModelRepository/issues/245

fix unrecognizedPropertyException in ConversionUtils

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/DataArray.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ParameterData.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/PythonJsonHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/RJsonHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/runner/RunnerNodeModel.java

Result of extensive Join-Testing. Here the workflow: 
[Test_Comb_Models_Chain.zip](https://github.com/SiLeBAT/FSK-Lab/files/6056894/Test_Comb_Models_Chain.zip)

Refince json data types

---

de.bund.bfr.knime.js/src/js/app/app.simulation.js

changes to app.simulation.js to fix 2 issues where
1. double type parameters turned into integers on change
2. double type parameters only min_value displayed

Applied Sascha's UI fix for Simulation Configurator

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/fskdbview/fskdbview.js
de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/fskdbview/FSKDBViewNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/fskdbview/FSKDBViewRepresentation.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/fskdbview/FSKDBViewValue.java

https://github.com/RakipInitiative/ModelRepository/issues/256

Fskdb view model re selection after saving

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/268

fix outport bug after reloading the joiner component

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSViewRepresentation.java

https://github.com/RakipInitiative/ModelRepository/issues/183

fix simulations deletion in the Editor

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSViewRepresentation.java

https://github.com/RakipInitiative/ModelRepository/issues/200

 Editor bug: combined model outport broken

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeDialog.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeSettings.java

This is done for performance reasons since saving parameters from R is
weirdly expensive.

added a checkbox in the Runner to toggle JSON parameter writing

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/275
https://github.com/RakipInitiative/ModelRepository/issues/274

fixing simulation scenarios generation

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/reader/ReaderNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/276

fix https://github.com/RakipInitiative/ModelRepository/issues/276

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/FskErrorMessages.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/ParameterJsonConversionException.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JsonHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/PythonJsonHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/RJsonHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java

[error_model_script.zip](https://github.com/SiLeBAT/FSK-Lab/files/6150423/error_model_script.zip)

add exception if model script fails in scriptHandler runSnippet()

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/fskdbview/FSKDBViewNodeDialog.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/fskdbview/FSKDBViewNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/284

fix shared setting between FSKDB view nodes

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/fskdbview/fskdbview.js

https://github.com/RakipInitiative/ModelRepository/issues/283
unfortunately, I can't reproduce the bug, but during testing I found a bug in editing the first selected model.
@schuelet could you please check if the problem still exist.

fix https://github.com/RakipInitiative/ModelRepository/issues/283

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js

related to https://app.zenhub.com/workspaces/online-model-repository-5e4bc0198f780f014bf8f3f3/issues/rakipinitiative/modelrepository/260

fix bug that prevents editing existing references

---

de.bund.bfr.knime.js/src/js/app/app.editable.mt.ArrayForm.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.SelectForm.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.TextareaForm.js

https://github.com/RakipInitiative/ModelRepository/issues/263

fix missing description of fields

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.ArrayForm.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js

https://github.com/RakipInitiative/ModelRepository/issues/295
I included here also issue https://github.com/RakipInitiative/ModelRepository/issues/294 as it's part of UI issue

fix a bug in saving panel with ArrayForm

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/FskPlugin.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/NodeUtils.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSViewRepresentation.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerViewRepresentation.java
de.bund.bfr.knime.js/src/js/app/app.table.mt.js
de.bund.bfr.knime.js/src/js/app/app.utils.js

FSK metadata joining service is not used anymore, merging metadata is on JS side.
related issues:
- https://github.com/RakipInitiative/ModelRepository/issues/244
- https://github.com/SiLeBAT/FSK-Lab/issues/819 
- https://github.com/RakipInitiative/ModelRepository/issues/297
- https://github.com/RakipInitiative/ModelRepository/issues/231
- https://github.com/RakipInitiative/ModelRepository/issues/232
- https://github.com/RakipInitiative/ModelRepository/issues/243

Java script metadata joining algorithm

---

.codeclimate.yml

The report at codeclimate is configured with the sonar plugin to generate the sonar report with security and Java issues.

Sonar report

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.Dialog.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.SimpleTable.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.TablePanel.js

https://github.com/RakipInitiative/ModelRepository/issues/296

fix a bug in editing reference dialog

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/RJsonHandler.java

I had to save the data of a parameter in a file because the Rcontroller can't handle large arrays (>100000 entries). It is not much slower.

store R JSON data in file to deal with large file data

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/reader/ReaderNodeModel.java

Reader now has flow variable pointing to downloaded file in workflow folder

add a path to flowvariable of Reader if model is downloaded

---

de.bund.bfr.knime.js/js-lib/bfr/fskapp/editor_data_1.0.0.js
de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js

At the request of @mfilter I removed the validation of emails in the editor.
@ahmadswaid please give this a thought if it breaks anything down the line, in my tests (runner -> writer->reader) it worked fine.

removed validation for email in editor

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js
de.bund.bfr.knime.fsklab.nodes/plugin.xml
de.bund.bfr.knime.js/js-lib/d3/d3.js
de.bund.bfr.knime.js/plugin.xml

https://github.com/RakipInitiative/ModelRepository/issues/309
I was able to remove all the annotation related to ports tooltip or select box (this was asked by @mfilter a while ago)
now I don't see the problem anymore.
I removed also the arrow heads in the SVG (if you see thart I keep only the target arrowhead or any thing else, just mention it)
I uploaded a simple test workflow here: knime://knime.mountpoint/FSKX_Testing/FSK-Lab_2.0/birt_report

Manipulate joiner svg

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/writer/WriterNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/310
Only the writter has the problem. where the `ScriptHandler` isn't used as `AutoCloseable`.

Use ScriptHandler with try-with-resource

---

de.bund.bfr.knime.js/src/scss/theme/modal-details.scss

related to point 1 in: https://github.com/SiLeBAT/FSK-Lab/issues/839

remove styles of Landing page script editor

---

.travis.yml

changed travis.yml to use another distribution of ubuntu

switched to dist: Xenial

---

de.bund.bfr.knime.js/src/js/app/app.mt.details.js
de.bund.bfr.knime.js/src/scss/theme/modal-details.scss

https://github.com/RakipInitiative/ModelRepository/issues/313

retrieve css for fskdbview pre tag

---

de.bund.bfr.knime.fsklab.metadata.model/src/metadata/SwaggerUtil.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

This will replace the model id with a UUID so that in the repository there won't be any duplicates.

apply a uuid to a model as an identifier

---

de.bund.bfr.knime.js/js-lib/bfr/fskapp/editor_data_1.0.0.js

Fix the tooltip issues in scope properties as described in #408.

Fix tooltips issues from #408

---

de.bund.bfr.knime.js/js-lib/bfr/fskapp/editor_data_1.0.0.js

The tooltip of parameter value is changed as in #487.

Change parameter value tooltip (#487)

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/writer/WriterNodeModel.java

The file extension of model plots in FSKX files should be SVG as in #493.

Fixes plot file extension

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeModel.java

https://github.com/SiLeBAT/FSK-Lab/issues/472

support "joining" of models without opening the view

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js

https://github.com/RakipInitiative/ModelRepository/issues/315

fix Joiner bug if modelName ends with space character

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/fskdbview/FSKDBViewNodeFactory.xml

https://github.com/SiLeBAT/FSK-Lab/pull/832#issuecomment-817550273
I created this workflow in KNIME Hub: https://kni.me/w/hvgtZc8MYdY7scqc
to demonstrate the functionality.
But this should changed in the future to BFR account.

FSKDB View Description

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/316

Adding Output parameter should not remove simulations

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/writer/WriterNodeModel.java

the writer used the same scriptHandler for all single models in a combined object creating problems if the models were written in different languages.

Writer bug joined models different languages

---

de.bund.bfr.knime.js/src/js/app/app.simulation.js
de.bund.bfr.knime.js/src/scss/theme/modal-details.scss

https://github.com/SiLeBAT/FSK-Lab/issues/398#event-4577356426

add global validation message area

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js

https://github.com/RakipInitiative/ModelRepository/issues/320

escape HTML special Chars

---

.travis.yml
gitlab_development.sh

Builds from the development branch are uploaded to silebat/repositories/development on Gitlab.

Development deploymentd

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/SiLeBAT/FSK-Lab/issues/875

retrieve originalMetadata from viewRep

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

@schuelet: the HF is related to the case when the user creates and saves a model  with the editor then tries to change the model type in the editor setting and tries to rerun the editor then the editor will fail.

HF: retrieve metadata after conversion takes place.

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSConfig.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeDialog.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSViewRepresentation.java

https://github.com/SiLeBAT/FSK-Lab/pull/879#issuecomment-829969499
https://github.com/SiLeBAT/FSK-Lab/issues/875
@schuelet this PR solved the issues:
- the one reported by @Thatsreallycool which is related to a reset on dialog saving.
- regenerate simulation for non-connected Editor.
- setting reset managment, that is an issue you notice when opening > saving > interactive view > save then problem will start.

Edited parameters are not stored in fsk object

---

de.bund.bfr.knime.js/src/js/app/app.ui.js

https://github.com/RakipInitiative/ModelRepository/issues/321
entering a string value will destroy the touchspin nature of the field and re-entering a numeric value will retreive it again

enable editing numeric parameters that contain text

---

de.bund.bfr.knime.js/src/js/app/app.mt.details.js

https://github.com/RakipInitiative/ModelRepository/issues/323

remove resource tab from FSKBD View (online mode)

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/fskdbview/fskdbview.js
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/324

enable edit button only if editor available in component other button

---

de.bund.bfr.knime.fsklab.nodes/META-INF/MANIFEST.MF
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/SiLeBAT/FSK-Lab/pull/884#issuecomment-830876769

fix bug deletion is not considered in the port object simulation

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/SiLeBAT/FSK-Lab/issues/889

fix CV for Format

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/fskdbview/fskdbview.js
de.bund.bfr.knime.js/src/js/app/app.table.mt.js

https://github.com/RakipInitiative/ModelRepository/issues/328

Db view issue execution time & upload date missing

---

gitlab_development.sh

The update site is moved to silebat/development on Gitlab server. The update site is placed under an update folder.

Development update site is split

---

de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java

Close open stream in FskService in case of error when importing RAKIP db.
https://codeclimate.com/github/SiLeBAT/FSK-Lab/de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java/source#issue-0df01403db49a456bdfc50f18505e6f3

Close open stream in FskService

---

gitlab_development.sh

My bad. I left previously the name of the former git repository in the script (repositories) and the folder could not be found.

Split dev site

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js

https://github.com/RakipInitiative/ModelRepository/issues/333

swap script by reorder

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

from discussion of https://github.com/SiLeBAT/FSK-Lab/pull/884
- adding a new parameter will be added to all simulations.
- editing the value of a parameter in the model math will change the value of that param in the default simulation.
- delete a parameter will delete that param from all simulations.

keep and update simulation on adding/edit/delete of parameter

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.css
de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/joiner/joiner.js

having input_conso as CONSTANT.
and It's not allowed to override this kind of parameters.

forbid constant parameters ovveride

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/writer/WriterNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/336

Add modification date when writing model

---

de.bund.bfr.knime.js/js-lib/bfr/fskapp/editor_data_1.0.0.js

reference is the shared document by Matthias.

rework the Editor UI schema

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/335

fix https://github.com/RakipInitiative/ModelRepository/issues/335

---

de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/RprofileManager.java
de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/server/RConnectionFactory.java

https://github.com/RakipInitiative/ModelRepository/issues/338
@schuelet: thanks for investigating this.

fix multi-runner issue on Linux

---

de.bund.bfr.knime.js/src/js/app/app.editable.mt.TablePanel.js

https://github.com/RakipInitiative/ModelRepository/issues/342

fix move up/down bug in tables

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/344

fix issue in saving downloaded files from remote with a valid file name

---

.github/workflows/build.yml
de.bund.bfr.knime.pmm.common.tests/src/de/bund/bfr/knime/pmm/common/units/CategoriesTest.java
de.bund.bfr.knime.pmm.common.tests/src/de/bund/bfr/knime/pmm/common/units/CategoryReaderTest.java

GitHub action

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/216

clean generated resources on reset

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js

https://github.com/RakipInitiative/ModelRepository/issues/346

check if validation errors exists before manipulating

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/fskdbview/fskdbview.js

https://github.com/RakipInitiative/ModelRepository/issues/349

cancel bulk simulation loading.only fetch it on model selection

---

de.bund.bfr.knime.js/js-lib/bfr/fskapp/editor_data_1.0.0.js

https://github.com/RakipInitiative/ModelRepository/issues/357

fix scope -> BMI type according to YAML type

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/356
For  https://github.com/RakipInitiative/ModelRepository/issues/355 DoseResponseModel has a unique attribute in generalInformation caled modelName unlike other models with attr (name) which prevents the convertion.

Editor bug changing model class to generic or DoseResponseModel

---

de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/fskdbview/fskdbview.js
de.bund.bfr.knime.js/src/js/app/app.mt.details.js
de.bund.bfr.knime.js/src/js/app/app.schemas.js
de.bund.bfr.knime.js/src/scss/theme/modal-details.scss

@schuelet  please note that I assumed that you will create an endpoint called `readme`
please let me know to change it if it dosen't work for you

Readme in detailsview in fskdb view

---

de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeDialog.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/358
Could you take a look at the workflow? I described the issue there:
[runner_simulation_settings.zip](https://github.com/SiLeBAT/FSK-Lab/files/7020020/runner_simulation_settings.zip)

delete nodeSettings simulation on reset

---

de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java
de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java

https://github.com/RakipInitiative/ModelRepository/issues/361

fixed editor issues with saving and some conversion issues
