- de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/nodes/newjoiner/joiner.js
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeModel.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerNodeSettings.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerViewRepresentation.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/JoinerViewValue.java
Remove the first and second model maths (model1Math and model2Math) in the Joiner
ViewValue and save instead the list of parameters of model 1 and model 2. Only the parameters are used in the view and the rest of the model math is unnecessary.  Also since the parameters are static and do not change, they are moved to the view representation.
> Move parameters to view representation

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/reader/ReaderNodeModel.java
had to insert a workaround in the reader node. Old python models had
their scripts ending with ".r" instead of the correct ".py".
> #115: python model from icpmf readable in 1.8.1

- de.bund.bfr.knime.fsklab.nodes/META-INF/MANIFEST.MF
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/PythonScriptHandler.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
#112 (modelrepository): the python interpreter (version2 or version3) is
now picked by using the information from the metadata (language written
in)
> 112 python interpreter now taken from metadata

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/simulator/JSSimulatorNodeModel.java
selected simulation was alway default when the Simulationation
Configurator JS View was opened after loading the workflow, now it shows
the corect simulation
> #632 wrong simulation in SimulationConfigurator JS View

- de.bund.bfr.knime.fsklab.nodes/META-INF/MANIFEST.MF
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/PythonScriptHandler.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
removed code that implemented the automatic selection of the Python
Interpreter (see #112 in RakipInitiative/modelRepository) due to
compatibility issues in KNIME 4.
> #136: restored code before commit #112

- de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/LibRegistry.java
The packages are installed on Mac like on Linux, by skipping minCRAN and using install.packages to the .fsk/library folder.
> Fix packages installation on Mac

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/PythonScriptHandler.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
- de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/LibRegistry.java
- de.bund.bfr.knime.update/category.xml
- features/de.bund.bfr.knime.fsklab.feature/feature.xml
- features/pom.xml
#674: mac support
#114: python auto picker (target 3)
#141: deprecated nodes no longer separate feature
> added #674, #112 and #141 for target platform 3 final release

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/reader/ReaderNodeModel.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/writer/WriterNodeModel.java
The reader and writer nodes were not supporting the R workspace for the
joined models (they did for individual models).
Test workflow: [689_missing_RData.zip](https://github.com/SiLeBAT/FSK-Lab/files/5327205/689_missing_RData.zip)
> R workspace not available after reading FSKX file

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/reader/ReaderNodeModel.java
Remove leftover code for created working directories in the reader node. These directories were replaced earlier with EnvironmentManagers.
> Remove unused working directory in Reader node

- de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
Sorry for the lack of tests. In the state of the service now, it is really hard to pull it out of KNIME to test it. (Need to work on it).
This join method takes the metadata of two models as an array in the body of the request and returns an empty generic model (for now). This endpoint will be finished with a joining algorithm that will return a filled generic model. This can be tested when KNIME is running with the following Java code:
```java
public static void main(String[] args) throws IOException {
ObjectMapper mapper = new ObjectMapper();
GenericModel exampleModel = new GenericModel();
GenericModel secondExample = new GenericModel();
Model[] models = { exampleModel, secondExample };
URL url = new URL("http://localhost:9999/joinMetadata");
HttpURLConnection conn = (HttpURLConnection) …
```
> Add POST method to joinMetadata (empty generic model for now)

- de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
The string literal "application/json" for the content type of many
responses is replaced with a constant (MIME_TYPE) in a single place.
> String literals should not be duplicated (java:S1192)

- de.bund.bfr.knime.fsklab.metadata.model.tests/src/metadata/ConversionUtilsTest.java
- de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java
This finishes work of https://github.com/SiLeBAT/FSK-Lab/pull/715. It adds full support for nested objects and arrays with recursion. Items in arrays are also check for compatibility and if possible are converted to the target schema.
The unittest has been extended to convert the example generic model to all the other model classes. Like before, the endpoint can be tested with the Java snippet:
```java
public class ConversionTest {
public static void main(String[] args) throws IOException {
ObjectMapper mapper = new ObjectMapper();
URL url = new URL("http://localhost:9999/convertMetadata/processModel");
HttpURLConnection conn = (HttpURLConnection) url.openConnection();
conn.setRequestMethod("POST");
conn.setRequestProperty("Content-Type", "application/json; utf-8"); …
```
> Finish conversion algorithm

- de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java
- de.bund.bfr.knime.fsklab.service/META-INF/MANIFEST.MF
- de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
Joining algorithm returns a GenericModel instead of JsonNode and several issues related to null and empty properties are fixed.
Example:
```java
public static void main(String[] args) throws IOException {
ObjectMapper mapper = new ObjectMapper().registerModule(new ThreeTenModule());
JsonNode exampleModel = mapper.readTree(new File("files/marcel/nautaCPM.json"));
JsonNode exampleModel2 = mapper.readTree(new File("files/marcel/medChallDRM.json"));
JsonNode[] models = { exampleModel, exampleModel2 };
URL url = new URL("http://localhost:9999/joinMetadata");
HttpURLConnection conn = (HttpURLConnection) url.openConnection();
conn.setRequestMethod("POST");
conn.setRequestProperty("Content-Type", "application/json; utf-8");
conn.setRequestProperty("Accept", "application/json"); …
```
> Joining algorithm fixes

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/PythonScriptHandler.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/joiner/JoinerNodeModel.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/runner/RunnerNodeModel.java
also: added error output for python (it was only implemented for R)
and fixed an issue with loading metadata into Joiner node
> copy generated resources to working directory

- de.bund.bfr.knime.fsklab.metadata.model.tests/src/metadata/ConversionUtilsTest.java
- de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java
- de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
The conversion and joining algorithms return deserialized model metadata instead of a JSON node.
> Change conversion and joining algorithms to return POJOs

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/runner/RunnerNodeModel.java
This is necessary when doing a join of first two models then with using another joiner to combine with a third one. 
in this case the runner was failing.
> support cascade joining

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v1_9/reader/ReaderNodeUtil.java
In the Reader, simulation (e.g. simulations/defaultsimulation.r) files would be considered part of the
"entries" to be loaded into the workingdirectory (environment). This bug
has the consequence, that the simulation.r (or .py) files end up in the
root folder of the written fskx file.
> fixed a bug, where simulation files are read into workingDirectory

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/FskErrorMessages.java
This is more a suggestion how we can manage error and warning messages that contain useful information to the user, e.g. what libraries can't be loaded or when they forget to install python integration or if there is a problem with the script and so on.
> Add a collection of error and warning messages with useful information

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
this leads to removal of user folder in .libPaths when executing multiple models in a row (combined model execution).
workflow: https://seafile.bfr.berlin/smart-link/5e75119b-f080-4f96-b785-26dcca8e3f3f/
linked to RakipInitiative/ModelRepository#270
> fixed bug where setting the path to .fsk folder is sometimes skipped

- de.bund.bfr.knime.js/src/js/app/app.simulation.js
- de.bund.bfr.knime.js/src/js/app/app.ui.js
switched forcestepdivisibility from 'round'(default) to 'none' to allow
uncapped precision of double parameters
> removed rounding of double parameters to allow more precision

- de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSViewRepresentation.java
- de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js
- de.bund.bfr.knime.js/src/js/app/app.editable.mt.SelectForm.js
- de.bund.bfr.knime.js/src/js/app/app.utils.js
Pass vocabularies as part of the view representation as a map of string arrays. SelectForm and InputForm are patched in the lib.
@ahmadswaid these changes are needed as the vocabularies will not work on the server. When the editor is opened in WebPortal the JS view tries to access the vocabularies in a localhost url and the client does not have FSK-Lab or the FskService. For this I needed to pass the vocabularies to the view so that they work on the server. Also, it was not working locally, I think because of a connection to a remote url. This is not acceptable because we cannot make a requirement of a permanent connection to use the editor. The editor should be fully functional offline.
Regarding my changes in the library, the problem is that now both InputForm and SelectForm use the …
> Pass vocabularies with JS repr

- de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
- de.bund.bfr.knime.js/js-lib/codemirror-5.49.2/lib/codemirror.js
- de.bund.bfr.knime.js/plugin.xml
- This PR is related to a bug in loading the instances of codemirror in Model, visualization scripts and readme in the editor.
- This bug can be observed in the editor only in a workflow deployed to the server and requested via the browser
- Desktop version of the editor was and still working fine.
- I included here a fix for scripts saving bug (https://github.com/RakipInitiative/ModelRepository/issues/287) as it's related somehow to this PR.
> fix bug in loading the code mirror instance in server mode

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
The language written in vocabulary is loaded in the editor instead of language. There was an error when creating the view representation and language written in was assigned the language vocabulary.
See https://github.com/RakipInitiative/ModelRepository/issues/288#event-4486721424
> Fix language written in vocabulary in editor

- de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
This needs to be removed once the implementation correctly uses
camelcase for the parameter classification.
Relates to the ticket https://app.zenhub.com/workspaces/online-model-repository-5e4bc0198f780f014bf8f3f3/issues/rakipinitiative/modelrepository/289
> parameter classification is converted to uppercase.

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java
checkbox "save to json file" was static and executing several runner nodes would overwrite the value causing failures for joined models.
> the static checkbox variable was a mistake. Fixed.

- de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
doSave function in editor.js would crash (exception) if a property didn't have the "includes" function
> Editor bug reference hotfix

- de.bund.bfr.knime.js/src/js/app/app.editable.mt.SimpleTable.js
When opening a model with the editor which contains a modification date [ null ] for whatever reason, the view doesn't load. I added a check for null in this case.
The problem occurs when adding a modification date but leaving it untouched (no actual date given). In that case, when writing the model, reading it again and trying to edit it, the error is thrown.
> added a check for null value for reading date objects

- de.bund.bfr.knime.js/src/js/app/app.editable.mt.SelectForm.js
- de.bund.bfr.knime.js/src/js/app/app.editable.mt.TablePanel.js
https://github.com/SiLeBAT/FSK-Lab/issues/357
https://github.com/SiLeBAT/FSK-Lab/issues/838
one finding here is that the list of parameter classification values have non-capital letters which leads to have the value not selected by editing, a ticket has to be created to fix the value in the controlled vocabularies if on is not exist yet.
> update selected value

- de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v2.0/editor/editor.js
dirty workaround to have parameter classification in the correct form (camel case). On getComponentValue, the classification is reset to upper case.
> camelize parameter classificatin on init, uppercase on exit

- de.bund.bfr.knime.fsklab.metadata.model/src/metadata/ConversionUtils.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/NodeUtils.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
https://github.com/RakipInitiative/ModelRepository/issues/304
- the NPM is caused by missing ModelMath in all model except generic model.
- this PR applies conversion utils to convert models from one model provided via port, this is usefull when connecting one node with some model type with another node and selecting another model type 
- also this conversion is applied on nodes with saved model metadata via `save as default or temporarily` which setup with a new model type.
> Editor bug picking a model from configuration dropdown menu fails node

- de.bund.bfr.knime.fsklab.nodes.tests/src/de/bund/bfr/knime/fsklab/nodes/NodeUtilsTest.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/NodeUtils.java
NodeUtils.initializeModel is updated to include general information and a model identifier for every model class. This will simplify initialising models in the nodes as they use NodeUtils and have to check later the identifier.
These are small changes but they will simplify a lot the changes needed in the editor.
> Sets identifier in initializeModel

- de.bund.bfr.knime.js/src/js/app/app.editable.mt.Dialog.js
- de.bund.bfr.knime.js/src/js/app/app.editable.mt.InputForm.js
- de.bund.bfr.knime.js/src/js/app/app.editable.mt.TablePanel.js
- de.bund.bfr.knime.js/src/js/app/app.table.js
https://github.com/SiLeBAT/FSK-Lab/issues/860
> fix: editor doesn't enable editing newly added rows in any table

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java
https://github.com/RakipInitiative/ModelRepository/issues/206
this is how I see thing has to be implemented if no svg generated out of visualization script or in case an error occurred there.
I'm open to any further changes.
> default svg generation if vis script doesn't generate one

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/reader/ReaderNodeUtil.java
Before, the map would not guarantee that all parameters are stored in
the correct order. This fixes the issue.
Observable in the workflow knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Model_new_Duarte
> rewrote the way, parameters are stored to avoid reordering issue

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/FskErrorMessages.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/ScriptHandler.java
File parameters that are not correctly declared or not accessible in the
workspace will no longer fail the execution of the node IF the user
doesn't use the model for joining or insists of writing the
paramater.json file.
> relaxed constraint of file parameters being accessible after execution

- de.bund.bfr.knime.js/src/js/app/app.simulation.js
In Simulation Configurator: when a model has a parameter which has a
minValue/maxValue of "-" then the view would still draw a slider from
NaN to NaN, making it impossible to edit this parameter. The NaN value
was also taken as new value when saving the Configurator.
> fixed a bug where min/maxValue of parameters would brick slider

- de.bund.bfr.knime.js/src/js/app/app.simulation.js
https://github.com/SiLeBAT/FSK-Lab/issues/489
@schuelet:
for interger and double only numeric values are allowed (already provided via the component) but I added Integer validation.
for other data types (in my point of view ) this will rais some limitation to the user freedom in providing the values. String values could be a literal string starting and end with `"` or could be an assignment to another string variable. there a lot of ways to define a matrix vector or boolean.
> validate integer values

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/runner/RunnerNodeModel.java
There seems to be no other way to determine which simulation the Runner
used on execution, so I added a flow-variable with that information.
> added a flow-variable to Runner outport saying which simulation it used

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/environment/ArchivedEnvironmentManager.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/reader/ReaderNodeUtil.java
@schuelet:
I did before this PR a stress test trying to access the same file from 200 reader nodes at the same time and that passed successfuly.
also run two copies of the huge reader workflow from two different knime instances, trying to access the same poor file hundreds of times concurrently from two different JVM and that passed successfuly.
I do see the CombineArchive issue only in the Reader if there other places please issue it to me.
> fix CombineArchive concurrent access issue

- de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
In case of SQL errors when importing the vocabularies tables.sql, the connection to the database is closed.
> Close leak to SQL file in FskService

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
https://github.com/RakipInitiative/ModelRepository/issues/334
the model have a model metadata type `GenericModel`  and the expected value is `genericModel` 
I don't know how this model is generated but it seems to be an old model.
I added a workaround like in ConversionUtils:ModelClass enum Line 66
> workaround for old models

- de.bund.bfr.knime.js/src/js/app/app.table.mt.js
@ahmadswaid I changed the frontend to fetch the executionTime/uploadDate in one step each. The endpoints were deployed last weekend. 
The loading time went down from 50s to 25s, so a noticable improvement. 25 seconds for a website to load is still too much, but it is a start.
> executiontime & uploadDate are downloaded in bulk

- de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/RScriptHandler.java
- de.bund.bfr.knime.fsklab.deprecatednodes/src-1_7_2/de/bund/bfr/knime/fsklab/nodes/v1_7_2/writer/WriterNodeModel.java
- de.bund.bfr.knime.fsklab.deprecatednodes/src-1_9_0/de/bund/bfr/knime/fsklab/nodes/v1_9/RScriptHandler.java
- de.bund.bfr.knime.fsklab.deprecatednodes/src-1_9_0/de/bund/bfr/knime/fsklab/v1_9/writer/WriterNodeModel.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/RScriptHandler.java
- de.bund.bfr.knime.fsklab.preferences/src/de/bund/bfr/knime/fsklab/preferences/PreferencePage.java
- de.bund.bfr.knime.fsklab.preferences/src/de/bund/bfr/knime/fsklab/preferences/RBinUtil.java
- de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/LibRegistry.java
- de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/client/RController.java
- de.bund.bfr.knime.fsklab.r/src/de/bund/bfr/knime/fsklab/r/server/RConnectionFactory.java
- There was a library check that tested each library if it is valid and that blew up the Rserve workspace everytime a model was running. With our new Rprofile implementation, that is now completely superfluous.
- More important, a new LibRegistry instance (and therefore a new RController) was created every time a Runner was executed. That meant, the old instance was not shut down properly. It is now ensured, that only one LibRegistry is open while needed.
- Also, each Rserve instance is now almost immeadiatly closed after executon (100ms). The 60000ms might have been useful for KNIME's R integration but we don't need that.
This massively improves memory management without changing too much of the code.
> Force terminate unused controllers

- de.bund.bfr.knime.js/src/js/app/app.table.mt.js
landingpage bugfix, related to the request of @mfilter where on a search with no hits, the model repository would still show all models.
> fixed bug, where on empty search result table would still show models

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/editor/FSKEditorJSNodeModel.java
- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/writer/WriterNodeModel.java
- changed Editor to apply an empty defaultSimulation
- changed Writer to accept model without name
- https://github.com/RakipInitiative/ModelRepository/issues/352
> editor always creates a minimum viable model for basic FSK nodes

- .github/workflows/build.yml
Previously, each push was built and deployed to gitlab, hopefully will
now be prevented.
> changed the github build.yml to only deploy on development

- de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/writer/WriterNodeModel.java
If a model name starts with a number and is joined, the writer would use
that name to create an SBML id. Since that id is not allowed to start
with a number, the id is cleaned up before writing the model.
> fixed bug in writer regarding model names starting with number
